spring.application.name=jobtrack
spring.datasource.url=jdbc:mysql://localhost:3306/jobtrack
spring.datasource.username=root
spring.datasource.password=rajeev7654()

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true